site_name: landuo

nav:
  - Home: README.md
  - Install: installation.md
  - Quickstart: quickstart.md
  - APIs:
    - lazyproperty: APIs/lazyproperty.md

theme:
    name: readthedocs

plugins:
  - search
  - mkdocstrings